language: node_js
node_js:
- 10.8
addons:
  apt:
    packages:
    - libgconf-2-4
cache:
  directories:
  - "~/.npm"
  - "~/.cache"
  override:
  - npm ci
  - npm run cy:verify
  - npm run cy:info
before-install:
- cd client && npm i && cd ..
install:
- npm i
script:
- npm run dev & wait-on http://localhost:3000
- npm run cy:run
- kill $(jobs -p) || true
deploy:
  provider: heroku
  api_key:
    secure: a28OVmHxwCW5x03XlQVJBpaZxNgSrYOKh4lumvAVfLHKZ/8qN9ZkHQpVMzDTboPCJ7fOmmaOdHpvRBQ1mW8aTllsgbQiH7Q9II9JMqq5ChSbvpOjskDsmTS54xJTqpetrKfYMr+ySzIV5gSdQyhNmykIaPTqkJy2hWb0v67E+iOYPknVpFlXetbJRmZTNzRMuiHO0M57ltQarvrg7VeRZHN9PnEtxoxHFXFO8x5GfHGstZkIZO8gX1mbH5J4wnjnGDjP9jFbzzkMDVBrAQvHZPUx/4+s8FB/6XkcDV7UKUzTkLxDxMOL72KpSsByp5ctVL0eDPnfkRpAjAo1a7+OKghnQRxr5/SMgyse9O/MI9kia7Agnp6XmjED7zS2YHNrAw+1V3Q6SiP4+4hedt14QYh0G+9An2k7fdI0yt8ar9FlCNsjQOOlE9Ou0mO3oPhoiwt9uvdzvzIJkGPMj0aUz+u0OCpzuRDRvhWQyc94S/eQt3IxZJynj5xvo4enPqBmDJ+dgTCGLCGo9L36du/vfFwaCJW2gLu2qhdU1BvPx6aPZbUGdw5UkiD8CdF9gvPCNbHpf6zX/IFwAZJI0iJLH3FHgKgqb60YS2ryG5bsSSK5beH+rnDuFXY9tIKIxw33cbbO2Wbgdh5Vcgpe4y8zM0tD7lgLuKSLQtOd/aYzi7A=
  app: mikeal-contact-keeper
  on:
    repo: miladmikeal/contact-keeper
