language: node_js
node_js:
  - 10.8
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  directories:
    - '~/.npm'
    - '~/.cache'
  override:
    - npm ci
    - npm run cy:verify
    - npm run cy:info
before-install:
  - cd client && npm i && cd ..
install:
  - npm i
script:
  - npm run dev & wait-on http://localhost:3000
  - npm run cy:run
  - kill $(jobs -p) || true
deploy:
  provider: heroku
  app: mikeal-contact-keeper
  api_key:
    secure: mu5F7eyImybdiscl8IFoN6mZ68xqMlfQAtJt6mnwqRpsajn9DldSbgjLeDwIzSzwwQh0E84QPZRvfDSYHyJ8WJ5htNBtJdIFwzM4RpYHdcluARsv5aVyJnj4PKVTpApGcwtTIcRkvRhdYuRiVW7K5SItUxhEV9CW7VzefAYXx4D5lB2OsAuKrdtSI/G2sCDq6ksnWDdiCP/9Om7LQXOdMs9tLaSCMoVzm4YG5UrFyZ3prZR6lr7ReAK0X5gh0OZa+IPHaeiPP+xXjn/OLmMy0FiRL+WVmKYITS2aYHp6/3mB5TbToBGuNYADiGA1P5VpGAikeGuILha0fIoUtCpnWt82xFBOc8xtmpc+tcacQt87eOkvLtIEGLscO4bZ6QXRKGLYAKTv+ddmG2KUxCuHDkUoLgY1eq3nWGJtFCtD292Zm/YTAFJkBeRhaGskEdPnbbal0baIRH3Y/ndOClOdl4essDfCFU1Ebna2SqSsRARyYQ1VHAcMclZGxrunR2c93tbDDSGSt/0OanRXQt57pzlJOLqIT3XO3HKtRegcbAGMXj0BTQk+rK8r6Ee1Qg9NP6WJfIQ2upSpHasEBSPT/z1I+luTB8BIgSC7UWVu6xIin7kjzUstNm50KVVaud+IvIVj9UVq16c73RHQdLZ/YMdYStPoEWnl8oozr93lSjY=
