language: node_js
node_js:
  - 10.8
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify
    - npm run cy:info
before-install:
  - cd client && npm i && cd ..
install:
  - npm i
script:
  - npm run server
  - npm run client
  - npm run cy:run
  - kill $(jobs -p) || true
