version: '3'

services:
  client:
    build:
      context: ./client
    ports:
      - '3006:3006'
    depends_on:
      - server
  server:
    build:
      context: .
    ports:
      - '5000:5000'
    environment:
      - DB=$DB
      - TEST_DB=$TEST_DB
      - JWT_SECRET=$JWT_SECRET


