version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - run: cd client && npm i && cd ..
      - run: npm ci
      - run: docker-compose build
      - run: docker-compose up & wait-on http://localhost:3000
      - run: npm run cy:run
workflows:
    build-and-test:
      jobs:
        - build-and-test